# Generated by Django 4.2.7 on 2023-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotable',
            name='date',
            field=models.DateField(default='2020-12-12'),
            preserve_default=False,
        ),
    ]
